#' Create triples from dataframe
#' 
#' This function parses the data from the parameter `data` and ensures compliance with the predicate mappings in `pred_tb`,
#' i.e. it ensures that the subject and object for each triple is correct.
#' 
#' It expects a dataframe containing additional columns `<class_name>_ID` for each class implied by the dataframe,
#' most likely generated by [identify_nodes()]. These ID columns contain the values that will be used as subjects in resulting triples.
#'
#' @param data [data.frame]
#' @param pred_tb `tibble` A tibble containing columns `predicate` (which contains the prefixed IRI), `rdfs:domain`, `rdfs:range` and `varname` (which contains the name of the variable in data corresponding to this predicate)
#' You can use [mapPredicates()] and [predicateTibble()] to generate this tibble.
#' 
#' @returns A dataframe containing columns `subject`, `predicate`, `object`
#' @export
#' 
#' @examples 
#' pred_tb <- tibble(
#'   predicate = c("prov:startedAtTime", "prov:endedAtTime", "rdf:type"),
#'   `rdfs:domain` = c(":Interview", ":Interview", "owl:Thing"),
#'   `rdfs:range` = c("xsd:dateTime", "xsd:dateTime", ":Interview"),
#'   varname = c("starttime", "endtime", "Interview_ID")
#' )
#' 
#' small_data <- tibble(
#'   starttime = c("2024-02-27 14:18:19", "2024-02-27 09:40:44"),
#'   endtime = c("2024-02-27 14:41:43", "2024-02-27 09:59:54"),
#'   Interview_ID = c("uuid:fe690b51-ee58-4294-b7b6-9f941b47b741", 
#'                    "uuid:0aa90b5e-14a7-46bc-a4cd-dc7306f03d61")
#' )
#' 
#' pivotLongerSPO(small_data, pred_tb)
#' @seealso [mapPredicates()], [predicateTibble()]
#' 
pivotLongerSPO <- function(data, pred_tb) {
  # preprocessing: convert all to character
  data <- mutate(data, across(everything(), ~as.character(.)))
  
  # get data in long format, with placeholder subjects (this snippet courtesy of ChatGPT)
  long_data <- data %>%
    rownames_to_column("subject") %>% 
    pivot_longer(cols = -subject,
                 names_to = "varname",
                 values_to = "object")
  
  # add correct predicate names
  long_data <- long_data %>%
    left_join(pred_tb, by = join_by(varname)) 

  # add predicate names that don't have corresponding variable names
  # these are predicates that map nodes to one another
  long_data <- long_data %>%
    select(subject) %>%
    distinct() %>%
    cross_join(pred_tb) %>% 
    left_join(long_data) 
  
  # add correct subjects
  sub_data <- addSubject(long_data, pred_tb)
  
  # add class membership triples
  class_data <- addClassMembership(long_data)

  # add correct objects for predicates that connect nodes, i.e. for which there is no corresponding column in the data
  obj_data <- addObject(long_data, pred_tb)
  interim <- sub_data %>% 
    filter(is.na(object)) %>% 
    select(-object) %>% 
    right_join(obj_data, by = c("inst_id", "predicate"))
  
  # select only SPO columns
  sub_data <- sub_data %>% 
    filter(!is.na(object)) %>% 
    select(subject, predicate, object)
  
  class_data <- class_data %>%
    select(subject, predicate, object)
  
  interim <- interim %>% 
    select(subject, predicate, object)
  
  spo_data <- rbind(sub_data, interim, class_data)
  
  return(spo_data)
}


#' Add SPO columns with correct subject
#'
#' Adjust dataframe to have correct subject according to domain and range specifications in `pred_tb`. Helper function used in [pivotLongerSPO()]. 
#' 
#' @param long_data [data.frame] Dataframe in long format. Should contain a `<classname>_ID` column for every class present in the domain and range specifications of `pred_tb`.
#' The `<classname>_ID` columns contain identifiers for each instance of the class. You can generate these IDs with [identify_nodes()].
#' @param pred_tb A tibble containing columns `predicate`, `rdfs:domain`, `rdfs:range` and `varname`. The value of `varname` is the name of the column in `data` corresponding to each `predicate`.
#' You can use [mapPredicates()] and [predicateTibble()] to generate this tibble.
#'
#' @return [data.frame] `long_data` with the correct subject for each row according to the domain of the predicate
#' 
#' @examples
#' small_pred_tb <- tibble(
#'   predicate = c("prov:startedAtTime", "prov:endedAtTime", "rdf:type"),
#'   `rdfs:domain` = c(":Survey", ":Survey", "owl:Thing"),
#'   `rdfs:range` = c("xsd:dateTime", "xsd:dateTime", ":Interview"),
#'   varname = c("starttime", "endtime", "Interview_ID")
#' )
#' 
#' long_data <- tibble(
#'   subject = c("1", "1", "1"),
#'   varname = c("starttime", "endtime", "Interview_ID"),
#'   object = c("2024-02-27 14:18:19", "2024-02-27 14:41:43", "uuid:fe690b51-ee58-4294-b7b6-9f941b47b741"),
#'   predicate = c("prov:startedAtTime", "prov:endedAtTime", "rdf:type"),
#'   `rdfs:domain` = c(":Survey", ":Survey", "owl:Thing"),
#'   `rdfs:range` = c("xsd:dateTime", "xsd:dateTime", ":Interview")
#' ) 
#' 
#' long_data <- addSubject(long_data, pred_tb)
#' 
#'# long_data
#'# A tibble: 3 × 6
#'#   subject                                    varname      object                 predicate          rdfs:domain  rdfs:range
#'#   <chr>                                      <chr>        <chr>                  <chr>              <chr>        <chr>
#'# 1 uuid:fe690b51-ee58-4294-b7b6-9f941b47b741  starttime    2024-02-27 14:18:19    prov:startedAtTime :Survey      xsd:dateTime
#'# 2 uuid:fe690b51-ee58-4294-b7b6-9f941b47b741. endtime      2024-02-27 14:41:43    prov:endedAtTime   :Survey      xsd:dateTime
#' 
#' @seealso [identify_nodes()], [pivotLongerSPO()]
addSubject <- function(long_data, pred_tb) {
  # add correct subjects according to specified rdfs:domain
  # select variable names for ID columns
  id_varnames <- pred_tb %>%
    select(varname) %>% 
    filter(pred_tb %>% 
             select(varname) %>% 
             pull() %>% 
             str_ends("_ID"))
  
  df <- data.frame()
  for (vn in id_varnames$varname) {
    classname <- str_split(vn, "_ID")[[1]][1] # select the first substring as a string (and not a vector)

    # this snippet courtesy of Claude
    current <- long_data %>%
      filter(str_ends(`rdfs:domain`, classname)) %>% 
      left_join(
        long_data %>% 
          filter(varname == vn) %>% 
          select(subject, new_subject = object),
        by = "subject"
      )
    
    df <- df %>% 
      rbind(current)
  }
  
  df <- df %>%
    rename(
      inst_id = subject,
      subject = new_subject,
    )
  
  return(df)
}

#' Add SPO columns that define class membership
#'
#' For each node, add a `<node_id> rdf:type <class>` triple. Helper function used in `pivotLongerSPO`. 
#' @param data [data.frame] Dataframe in long format. Should contain a `<classname>_ID` column for every class present.
#'
#' @return [data.frame] dataframe containing three columns (i.a.): `subject`, `predicate`, `object`; predicate = "rdf:type"
addClassMembership <- function(data) {
  data <- data %>% 
    filter(predicate == "rdf:type") %>% # select rdf:type triples that indicate class membership
    select(-subject) %>%  # prevent R from complaining about duplicate columns
    rename(subject = object) %>% # create triples
    mutate(predicate = "rdf:type") %>% 
    mutate(object = `rdfs:range`)
  
  return(data)
}

#' Add SPO columns with correct object
#'
#' Adjust dataframe to have correct object according to domain and range specifications in `pred_tb`. Helper function used in [pivotLongerSPO()].
#' 
#' @param long_data [data.frame] Dataframe in long format. Should contain a `<classname>_ID` column for every class present in the domain and range specifications of `pred_tb`.
#' The `<classname>_ID` columns contain identifiers for each instance of the class. You can generate these with [identify_nodes()].
#' @param pred_tb A tibble containing columns `predicate`, `rdfs:domain`, `rdfs:range` and `varname`. The value of `varname` is the name of the column in `data` corresponding to each `predicate`.
#' You can use [mapPredicates()] and [predicateTibble()] to generate this tibble.
#'
#' @return [data.frame] `long_data` with the correct object according to the domain of the predicate. Values are only added where the `object` column in `long_data` is empty.
#' @seealso [addSubject()] for examples
addObject <- function(long_data, pred_tb) {
  # select variable names for ID columns
  id_varnames <- pred_tb %>%
    select(varname) %>% 
    filter(pred_tb %>% 
             select(varname) %>% 
             pull() %>% 
             str_ends("_ID"))
  
  # only add objects for triples that have no object yet (NA)
  objectify <- long_data %>% 
    filter(is.na(object))
  
  df <- data.frame()
  for (vn in id_varnames$varname) {
    classname <- str_split(vn, "_ID")[[1]][1] # select the first substring as a string (and not a vector)
    
    # this snippet courtesy of Claude
    current <- objectify %>%
      filter(str_ends(`rdfs:range`, classname)) %>% 
      left_join(
        long_data %>%
          filter(varname == vn) %>%
          select(subject, new_object = object),
        by = "subject"
      )
    
    df <- df %>% 
      rbind(current)
  }
  
  df <- df %>%
    select(-object) %>% 
    rename(
      inst_id = subject,
      object = new_object
    )
  
  return(df)
}
