#' This function returns a dataframe containing columns "subject", "predicate", "object"
#' It parses the data from the parameter data and ensures compliance with the predicate mappings in pred_tb,
#' i.e. it ensures that the subject and object for each triple is correct.
#' It expects a dataframe containing additional columns <class_name>_ID for each class implied by the dataframe,
#' most likely generated by `identify_nodes`. These ID columns contain the values that will be used as subjects in resulting triples.
#'
#' @param data
#' @param pred_tb A tibble containing columns predIRI, rdfs:domain, rdfs:range and varname (which contains name of the variable in data corresponding to this predicate)
#' 
#' @returns A dataframe containing columns "subject", "predicate", "object"
#' @export
#' 
#' @examples TODO insert here from full workflow
pivotLongerSPO <- function(data, pred_tb) {
  # preprocessing: convert all to character
  data <- mutate(data, across(everything(), ~as.character(.)))
  
  # get data in long format, with placeholder subjects (this snippet courtesy of ChatGPT)
  long_data <- data %>%
    rownames_to_column("subject") %>% 
    pivot_longer(cols = -subject,
                 names_to = "varname",
                 values_to = "object")
  
  # add correct predicate names
  long_data <- long_data %>%
    left_join(pred_tb, by = join_by(varname)) 

  # add predicate names that don't have corresponding variable names
  long_data <- long_data %>%
    select(subject) %>%
    distinct() %>%
    cross_join(pred_tib) %>% 
    left_join(long_data) 
  
  # add correct subjects for custom classes (i.e. ID columns ending with _ID)
  sub_data <- addSubject(long_data, pred_tb)
  
  # add correct objects for predicates that connect nodes, i.e. for which there is no corresponding column
  obj_data <- addObject(sub_data, pred_tb)

  # add class membership triples
  class_data <- addClassMembership(long_data)

  spo_data <- rbind(sub_data %>% filter(!is.na(object)), obj_data, class_data)
  
  spo_data <- spo_data %>% 
    rename(predicate = predIRI) %>% 
    select(subject, predicate, object)
  return(spo_data)
}


#' Add SPO columns with correct subject
#'
#' Adjust dataframe to have correct subject per domain and range specifications in pred_tb
#' 
#' @param long_data 
#' @param pred_tb A tibble containing columns predIRI, rdfs:domain, rdfs:range and varname (which contains name of the variable in data corresponding to this predicate)
#'
#' @return [data.frame]
addSubject <- function(long_data, pred_tb) {
  # add correct subjects according to specified rdfs:domain
  # select variable names for ID columns
  id_varnames <- pred_tb %>%
    select(varname) %>% 
    filter(pred_tb %>% 
             select(varname) %>% 
             pull() %>% 
             str_ends("_ID"))
  
  df <- data.frame()
  for (vn in id_varnames$varname) {
    classname <- str_split(vn, "_ID")[[1]][1] # select the first substring as a string (and not a vector)

    # this snippet courtesy of Claude
    current <- long_data %>%
      filter(str_ends(`rdfs:domain`, classname)) %>% 
      left_join(
        long_data %>% 
          filter(varname == vn) %>% 
          select(subject, new_subject = object),
        by = "subject"
      )
    
    df <- df %>% 
      rbind(current)
  }
  
  df <- df %>%
    select(-subject) %>% 
    rename(
      subject = new_subject,
    ) %>% 
    select(names(long_data))
  
  return(df)
}

#' Add SPO columns that define class membership
#'
#' For each node, add a "<node_id> rdf:type <class>" triple. Helper function used in `pivotLongerSPO` 
#' @param data [data.frame] Long dataframe
#'
#' @return dataframe with three columns: "subject", "predicate", "object"; predicate = "rdf:type"
addClassMembership <- function(data) {
  data <- data %>% 
    filter(predIRI == "rdf:type") %>% # select rdf:type triples that indicate class membership
    select(-subject) %>%  # prevent R from complaining about duplicate columns
    rename(subject = object) %>% # create triples
    mutate(predIRI = "rdf:type") %>% 
    mutate(object = `rdfs:range`)
  
  return(data)
}

addObject <- function(long_data, pred_tb) {
  # add correct subjects according to specified rdfs:domain
  # select variable names for ID columns
  id_varnames <- pred_tb %>%
    select(varname) %>% 
    filter(pred_tb %>% 
             select(varname) %>% 
             pull() %>% 
             str_ends("_ID"))
  
  # only add objects for triples that have no object yet (NA)
  objectify <- long_data %>% 
    filter(is.na(object))
  
  df <- data.frame()
  for (vn in id_varnames$varname) {
    classname <- str_split(vn, "_ID")[[1]][1] # select the first substring as a string (and not a vector)

    # this snippet courtesy of Claude
    current <- objectify %>%
      filter(str_ends(`rdfs:range`, classname)) %>% 
      left_join(
        objectify %>%
          filter(varname == vn) %>%
          select(subject, new_object = object),
        by = "subject"
      )
    
    df <- df %>% 
      rbind(current)
  }
  
  df <- df %>%
    select(-object) %>% 
    rename(
      object = new_object
    )
  
  return(df)
}
