#' Create specified predicate mappings from dataframe 
#' 
#' This function maps the columns of a dataframe to predicate specifications using conventions compatible with Fluree V3
#' These predicates can be used to define a schema for Fluree transactions.
#' Each predicate mapping specifies
#' 1. predIRI: the IRI of the predicate in full. Inclusion of `@context` to incorporate ontology prefixes is handled later in the data pipeline
#' 2. the domain of the predicate as IRI
#' 3. the range of the predicate as IRI
#' 4. the corresponding column (variable) name in the dataframe
#' This function just builds the predicate specification. The heavy lifting (the actual content of the specification) still has to be done manually -
#' In future (post 12/2024), the goal is to automate this process to a greater degree.
#'
#' @param varnames [character] Column names corresponding to predicates
#' @param predIRIs [character] Complete predicate IRIs
#' @param domains [character] Complete domain IRIs
#' @param ranges [character] Complete range IRIs
#' 
#' @returns The predicate mappings as a list of named lists. Each list has entries:
#' predIRI, http://www.w3.org/2000/01/rdf-schema#domain, http://www.w3.org/2000/01/rdf-schema#range, and varname (column name corresponding to this predicate mapping)
#' @export
mapPredicates <- function(varnames, predIRIs, domains, ranges){
  schema_list <- list()
  for(i in 1:length(varnames)){
    schema_list[[i]] <- list(
      "predIRI" = predIRIs[i],
      "http://www.w3.org/2000/01/rdf-schema#domain" = domains[i],
      "http://www.w3.org/2000/01/rdf-schema#range" = ranges[i],
      "varname" = varnames[i]
    )
  }
  return(schema_list)
}

# TODO documentation
specIDPredicates <- function(data, id_tb) {
  id_varnames <- id_tb %>% select(var_id_name) %>% pull()
  id_IRIs <- rep("http://www.w3.org/1999/02/22-rdf-syntax-ns#type", nrow(id_tb))
  id_domains <- rep("http://www.w3.org/2002/07/owl#Thing", nrow(id_tb))
  id_ranges <- id_tb %>% select(type) %>% pull()
  
  id_predlist <- mapPredicates(id_varnames, id_IRIs, id_domains, id_ranges)
  
  return(id_predlist)
}

#' Convert predicate mapping list to a tibble
#'
#' @param schema_list Predicate mapping list of lists, most likely generated by `mapPredicates` 
#'
#' @return Predicate mapping as a tibble. Columns: predicate IRI, domain, range, corresponding column name
#' @export
#'
#' @examples
#' small_predlist <- mapPredicates(varnames, predIRIs, domains, ranges)
#' pred_tb <- predicateTibble(small_predlist)
predicateTibble <- function(schema_list) {
  pred_tb <- tibble(
    schema_list = schema_list
  ) %>%
    unnest_wider(schema_list)
  
  return(pred_tb)
}
