#' This function returns a dataframe containing columns "subject", "predicate", "object"
#' It parses the data from the parameter data and ensures compliance with the predicate mappings in pred_tb,
#' i.e. it ensures that the subject and object for each triple is correct.
#' It expects a dataframe containing additional columns <class_name>_ID for each class implied by the dataframe,
#' most likely generated by `identify_nodes`. These ID columns contain the values that will be used as subjects in resulting triples.
#'
#' @param data
#' @param pred_tb A tibble containing columns predIRI, rdfs:domain, rdfs:range and varname (which contains name of the variable in data corresponding to this predicate)
#' 
#' @returns A dataframe containing columns "subject", "predicate", "object"
#' @export
#' 
#' @examples TODO insert here from full workflow
pivotLongerSPO <- function(data, pred_tb) {
  # preprocessing: convert all to character
  data <- mutate(data, across(everything(), ~as.character(.)))
  
  # get data in long format, with placeholder subjects (this snippet courtesy of ChatGPT)
  long_data <- data %>%
    rownames_to_column("subject") %>% 
    pivot_longer(cols = -subject,
                 names_to = "varname",
                 values_to = "object")
  
  # add correct predicate names
  long_data <- long_data %>%
    right_join(pred_tb, by = join_by(varname)) 
  
  # add correct subjects according to specified rdfs:domain
  
  # select variable names for ID columns
  id_varnames <- pred_tb %>%
    select(varname) %>% 
    filter(pred_tb %>% 
             select(varname) %>% 
             pull() %>% 
             str_ends("_ID"))
  
  df <- data.frame()
  for (vn in id_varnames$varname) {
    print(paste("besig met", vn))
    
    classname <- str_split(vn, "_ID")[[1]][1] # select the first 
    print(classname)
    
    # this snippet courtesy of Claude
    current <- long_data %>%
      filter(str_ends(`rdfs:domain`, classname)) %>% 
      left_join(
        long_data %>% 
          filter(varname == vn) %>% 
          select(subject, new_subject = object),
        by = "subject"
      )
    
    df <- df %>% 
      rbind(current)
  }
  
  df <- df %>%
    select(-subject) %>% 
    rename(
      subject = new_subject,
      predicate = predIRI
    ) %>%
    select(subject, predicate, object)
  
  return(df)
}
