#' Replace IRIs with prefixes
#' 
#' This function courtesy of Claude. 
#' This function replaces verbose IRIs in predicate mappings with their prefixed versions.
#' To do this, it uses the context list below, as well as additional prefix mappings provided in @param add_context
#' context <- list(
#' ":" = "https://nova.org.za/nova-o#",
#' "aia" = "http://purl.org/aiaontology#",
#' "owl" = "http://www.w3.org/2002/07/owl#",
#' "rdf" = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
#' "xml" = "http://www.w3.org/XML/1998/namespace",
#' "xsd" = "http://www.w3.org/2001/XMLSchema#",
#' "foaf" = "http://xmlns.com/foaf/spec/#term_",
#' "prov" = "http://www.w3.org/ns/prov#",
#' "rdfs" = "http://www.w3.org/2000/01/rdf-schema#",
#' "time" = "https://www.w3.org/2006/time#",
#' "vcard" = "http://www.w3.org/TR/vcard-rdf/#",
#' "base" = "https://nova.org.za/nova-o"
#' )
#' @param data Predicate mappings. The function expects a list of lists, most likely generated by `mapPredicates`
#' @param add_context Additional prefix mappings as a named list. 
#'
#' @return Prefixed predicate mappings
#' @export
#'
#' @examples
#' small_predlist <- mapPredicates(varnames, predIRIs, domains, ranges)
#' geprefix <- replace_iris_with_prefixes(small_predlist)
replace_iris_with_prefixes <- function(data, add_context = NULL) {
  context <- list(
    ":" = "https://nova.org.za/nova-o#",
    "aia" = "http://purl.org/aiaontology#",
    "owl" = "http://www.w3.org/2002/07/owl#",
    "rdf" = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "xml" = "http://www.w3.org/XML/1998/namespace",
    "xsd" = "http://www.w3.org/2001/XMLSchema#",
    "foaf" = "http://xmlns.com/foaf/spec/#term_",
    "prov" = "http://www.w3.org/ns/prov#",
    "rdfs" = "http://www.w3.org/2000/01/rdf-schema#",
    "time" = "https://www.w3.org/2006/time#", 
    "vcard" = "http://www.w3.org/TR/vcard-rdf/#",
    "base" = "https://nova.org.za/nova-o"
  )
  
  # add additional context
  context <- c(context, add_context)
  
  # Function to replace a single IRI with its prefix
  replace_iri <- function(value, context) {
    # Handle NA values
    if (is.na(value)) return(value)
    
    # Go through each context prefix
    for (prefix_name in names(context)) {
      base_iri <- context[[prefix_name]]
      
      # Check if the value starts with the base IRI
      if (startsWith(value, base_iri)) {
        # for the base ontology IRI, the prefix is only :
        if (prefix_name == ":") {
          return(gsub(
          paste0("^", base_iri), 
          prefix_name, 
          value
        ))
        }
        
        # Replace the base IRI with its prefix
        return(gsub(
          paste0("^", base_iri), 
          paste0(prefix_name, ":"), 
          value
        ))
      }
    }
    
    # If no matching IRI found, return original value
    return(value)
  }
  
  # Process each list in the input
  lapply(data, function(list_item) {
    # Process each named element in the list
    processed_item <- lapply(names(list_item), function(name) {
      value <- list_item[[name]]
      
      # Replace IRI in the name
      processed_name <- replace_iri(name, context)
      
      # Replace IRI in the value if it's a character
      processed_value <- if (is.character(value)) replace_iri(value, context) else value
      
      # Create a named element with processed name and value
      setNames(list(processed_value), processed_name)
    })
    
    # Flatten the list and convert back to a list
    do.call(c, processed_item)
  })
}
