#' Replace IRIs with prefixes
#' 
#' This function courtesy of ChatGPT. 
#' This function replaces verbose IRIs in predicate mappings with their prefixed versions. 
#' To do this, it uses the context list below, as well as additional prefix mappings provided in `add_context`
#' context <- c(
#' ":" = "https://nova.org.za/nova-o#",
#' "aia" = "http://purl.org/aiaontology#",
#' "owl" = "http://www.w3.org/2002/07/owl#",
#' "rdf" = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
#' "xml" = "http://www.w3.org/XML/1998/namespace",
#' "xsd" = "http://www.w3.org/2001/XMLSchema#",
#' "foaf" = "http://xmlns.com/foaf/spec/#term_",
#' "prov" = "http://www.w3.org/ns/prov#",
#' "rdfs" = "http://www.w3.org/2000/01/rdf-schema#",
#' "time" = "https://www.w3.org/2006/time#",
#' "vcard" = "http://www.w3.org/TR/vcard-rdf/#",
#' "base" = "https://nova.org.za/nova-o"
#' )
#' @param data [tibble] Predicate mappings, most likely generated by [mapPredicates()]
#' @param add_context [character] Additional prefix mappings as a named vector. 
#'
#' @return [named list] Containing `data` = prefixed predicate mappings, `context` = context as a tibble
#' @export
#'
#' @examples
#' small_pred <- mapPredicates(varnames, predIRIs, domains, ranges)
#' geprefix <- prefixIRIs(small_pred)
#' 
prefixIRIs <- function(data, add_context = NULL) {
  context <- c(
    ":" = "https://nova.org.za/nova-o#",
    "aia" = "http://purl.org/aiaontology#",
    "owl" = "http://www.w3.org/2002/07/owl#",
    "rdf" = "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "xml" = "http://www.w3.org/XML/1998/namespace",
    "xsd" = "http://www.w3.org/2001/XMLSchema#",
    "foaf" = "http://xmlns.com/foaf/spec/#term_",
    "prov" = "http://www.w3.org/ns/prov#",
    "rdfs" = "http://www.w3.org/2000/01/rdf-schema#",
    "time" = "https://www.w3.org/2006/time#", 
    "vcard" = "https://www.w3.org/2006/vcard/ns#",
    "base" = "https://nova.org.za/nova-o"
  )
  
  # add additional context
  context <- c(context, add_context)
  
  # helper function
  replace_with_key <- function(context, char_vector) {
    # First, replace the special case (if the URL matches the value of ":") with ":"
    char_vector <- gsub(context[":"], ":", char_vector)
    
    # Then, replace other URLs with their corresponding keys followed by ":"
    for (key in names(context)) {
      if (key != ":") {
        char_vector <- gsub(context[key], paste0(key, ":"), char_vector)
      }
    }
    
    return(char_vector)
  }
  
  # modify data
  data_modified <- data %>%
    rename_with(~replace_with_key(context, .)) %>%
    mutate(across(everything(), ~replace_with_key(context, .)))
  
  ctx_tib <- tibble(
    prefix = names(context),
    IRI = unlist(context)
  )
  
  return(list(output = data_modified, context = ctx_tib))
}
